env:
  name: prod
ingress:
  apiHostname: users.travelzap.com
secret:
  name: users-service-prod-doppler-secret
hpa:
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
