env:
  name: staging
ingress:
  apiHostname: users-staging.travelzap.com
secret:
  name: users-service-staging-doppler-secret
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70
