apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.name }}-https-only
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-ingress-https
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{.Values.ingress.apiHostname}}`)
      kind: Rule
      services:
        - name: {{ .Values.name }}
          port: 80
  tls:
    secretName: {{ .Values.name }}-cert

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-ingress-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      middlewares:
        - name: {{ .Values.name }}-https-only
      match: Host(`{{ .Values.ingress.apiHostname }}`)
      services:
        - name: {{ .Values.name }}
          port: 80
