apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 44000