apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: users-service-cert
  namespace: staging
spec:
  secretName: users-service-cert
  commonName: users-staging.travelzap.com
  dnsNames:
    - users-staging.travelzap.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

