apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tzneststarter-cert
  namespace: staging
spec:
  secretName: tzneststarter-cert
  commonName: starter-staging.travelzap.com
  dnsNames:
    - starter-staging.travelzap.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

