apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tzneststarter-cert
  namespace: staging
spec:
  secretName: tzneststarter-cert
  commonName: starter.travelzap.com
  dnsNames:
    - starter.travelzap.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

