apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: users-service-cert
  namespace: prod
spec:
  secretName: users-service-cert
  commonName: users.travelzap.com
  dnsNames:
    - users.travelzap.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

