apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    preferredChain: 'ISRG Root X1'
    email: d.foss@destify.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: lets-encrypt-prod-account-key
    solvers:
      - http01:
          ingress: {}
